@startuml

actor "Operador"

rectangle "Sistema Agro" {
}

"Operador" --> "Sistema Agro" : Registra máquina
"Operador" --> "Sistema Agro" : Informa horas trabalhadas
"Sistema Agro" --> "Operador" : Exibe horas registradas

@enduml

